### ISSUE TITLE
How to connect with blazegraph? 

### ISSUE THREAD

**Issue by matheusriios** [bergos/sparql-http-client#27]
```
constructor() {
    this.client = new SparqlClient({
      endpointUrl: 'http://db:9999/bigdata/sparql',
    });
  }
```

Error: 
```
FetchError {
   message: 'request to http://db:9999/bigdata/sparql failed, reason: getaddrinfo ENOTFOUND db',
   type: 'system',
   errno: 'ENOTFOUND',
   code: 'ENOTFOUND'
```

**Comment by tpluscode** [comment]
This means that `db` is not recognised as host. Are you running this in docker maybe?

**Comment by matheusriios** [comment]
Yes, by docker.

My config of docker-compose:

```yaml
  db:
    hostname: db
    image: lyrasis/blazegraph:2.1.5
    ports: 
      - 9999:8080

```
